palavra = input('digite algo: ')
print('o tipo primitivo desse valor é ', type(palavra))
print('só tem espacos: ', palavra.isspace())
print('é um numero: ', palavra.isnumeric())
print('é alfabetico', palavra.isalpha())
print('é alfanumerico', palavra.isalnum())
print('está em maiusculo: ', palavra.isupper())
print('está em minusculo: ', palavra.islower())
print('está capitalizada: ', palavra.istitle())
